config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :transactions

  resources :accounts

  resources :account_types

  resources :users

end

app/controllers/account_types_controller.rb
class AccountTypesController < ApplicationController
  before_action :set_account_type, only: [:show, :edit, :update, :destroy]

  # GET /account_types
  # GET /account_types.json
  def index
    @account_types = AccountType.all
  end

  # GET /account_types/1
  # GET /account_types/1.json
  def show
  end

  # GET /account_types/new
  def new
    @account_type = AccountType.new
  end

  # GET /account_types/1/edit
  def edit
  end

  # POST /account_types
  # POST /account_types.json
  def create
    @account_type = AccountType.new(account_type_params)

    respond_to do |format|
      if @account_type.save
        format.html { redirect_to @account_type, notice: 'Account type was successfully created.' }
        format.json { render :show, status: :created, location: @account_type }
      else
        format.html { render :new }
        format.json { render json: @account_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_types/1
  # PATCH/PUT /account_types/1.json
  def update
    respond_to do |format|
      if @account_type.update(account_type_params)
        format.html { redirect_to @account_type, notice: 'Account type was successfully updated.' }
        format.json { render :show, status: :ok, location: @account_type }
      else
        format.html { render :edit }
        format.json { render json: @account_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_types/1
  # DELETE /account_types/1.json
  def destroy
    @account_type.destroy
    respond_to do |format|
      format.html { redirect_to account_types_url, notice: 'Account type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_type
      @account_type = AccountType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_type_params
      params.require(:account_type).permit(:name, :lhs_attr, :rhs_attr, :plus_attr, :minus_attr)
    end
end

app/helpers/account_types_helper.rb
module AccountTypesHelper
end

app/views/account_types/_form.html.erb
<%= form_for(@account_type) do |f| %>
  <% if @account_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account_type.errors.count, "error") %> prohibited this account_type from being saved:</h2>

      <ul>
      <% @account_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lhs_attr %><br>
    <%= f.check_box :lhs_attr %>
  </div>
  <div class="field">
    <%= f.label :rhs_attr %><br>
    <%= f.check_box :rhs_attr %>
  </div>
  <div class="field">
    <%= f.label :plus_attr %><br>
    <%= f.check_box :plus_attr %>
  </div>
  <div class="field">
    <%= f.label :minus_attr %><br>
    <%= f.check_box :minus_attr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/account_types/edit.html.erb
<h1>Editing account_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @account_type %> |
<%= link_to 'Back', account_types_path %>

app/views/account_types/index.html.erb
<h1>Listing account_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lhs attr</th>
      <th>Rhs attr</th>
      <th>Plus attr</th>
      <th>Minus attr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_types.each do |account_type| %>
      <tr>
        <td><%= account_type.name %></td>
        <td><%= account_type.lhs_attr %></td>
        <td><%= account_type.rhs_attr %></td>
        <td><%= account_type.plus_attr %></td>
        <td><%= account_type.minus_attr %></td>
        <td><%= link_to 'Show', account_type %></td>
        <td><%= link_to 'Edit', edit_account_type_path(account_type) %></td>
        <td><%= link_to 'Destroy', account_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account type', new_account_type_path %>

app/views/account_types/new.html.erb
<h1>New account_type</h1>

<%= render 'form' %>

<%= link_to 'Back', account_types_path %>

app/views/account_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account_type.name %>
</p>

<p>
  <strong>Lhs attr:</strong>
  <%= @account_type.lhs_attr %>
</p>

<p>
  <strong>Rhs attr:</strong>
  <%= @account_type.rhs_attr %>
</p>

<p>
  <strong>Plus attr:</strong>
  <%= @account_type.plus_attr %>
</p>

<p>
  <strong>Minus attr:</strong>
  <%= @account_type.minus_attr %>
</p>

<%= link_to 'Edit', edit_account_type_path(@account_type) %> |
<%= link_to 'Back', account_types_path %>